name: PR Close
on:
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-changelog
  cancel-in-progress: true

jobs:
  GenerateChangelog:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.CHANGELOG_PAT }}
          fetch-depth: 0
          submodules: false
          ref: main
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
      # * CHANGELOG
      - run: go install github.com/hashicorp/go-changelog/cmd/changelog-build@latest
      - run: bash .github/changelog/generate-changelog.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update CHANGELOG.md"
          commit_options: '--no-verify --signoff'
          push_options: '--force'
          file_pattern: CHANGELOG.md
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: Changelog Bot <github-actions[bot]@users.noreply.github.com>
